# Generated by Django 4.0.5 on 2022-06-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_options_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='mobile',
            new_name='mobile_no',
        ),
    ]
